steps:
  # Build frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/vue-multiagent-frontend:latest', './frontend']
  
  # Build backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/vue-multiagent-backend:latest', './backend']
  
  # Push images
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/vue-multiagent-frontend:latest']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/vue-multiagent-backend:latest']
  
  # Deploy backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'vue-multiagent-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/vue-multiagent-backend:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'DB_USER=root,DB_NAME=multiagent_db,USE_CLOUD_SQL=true,FRONTEND_URL=https://vue-multiagent-frontend-887330536517.us-central1.run.app'
      - '--set-secrets'
      - 'OPENAI_API_KEY=openai-api-key:latest,SECRET_KEY=jwt-secret-key:latest,DB_PASS=db-password:latest,SMTP_USER=SMTP_USER:latest,SMTP_PASSWORD=SMTP_PASSWORD:latest,FROM_EMAIL=FROM_EMAIL:latest,INSTANCE_CONNECTION_NAME=INSTANCE_CONNECTION_NAME:latest'
      - '--timeout'
      - '300'
      - '--memory'
      - '512Mi'
  


images:
  - 'gcr.io/$PROJECT_ID/vue-multiagent-frontend:latest'
  - 'gcr.io/$PROJECT_ID/vue-multiagent-backend:latest'